export const GET_MOVIE_LIST_SUCCESS = "GET_MOVIE_LIST_SUCCESS";
export const GET_MOVIE_LIST_FAILED = "GET_MOVIE_LIST_FAILED";

export const GET_MOVIE_DETAIL_SUCCESS = "GET_MOVIE_DETAIL_SUCCESS";
export const GET_MOVIE_DETAIL_FAILED = "GET_MOVIE_DETAIL_FAILED";

export const GET_NEW_LIST_SUCCESS = "GET_NEW_LIST_SUCCESS";
export const GET_NEW_LIST_FAILED = "GET_NEW_LIST_FAILED";

export const GET_NEW_DETAIL_SUCCESS = "GET_NEW_DETAIL_SUCCESS";
export const GET_NEW_DETAIL_FAILED = "GET_NEW_DETAIL_FAILED";

export const GET_MOVIE_TIME_SUCCESS = "GET_MOVIE_TIME_SUCCESS";
export const GET_MOVIE_TIME_FAILED = "GET_MOVIE_TIME_FAILED";
